[#assign routeID  = timesTable.getRouteID()?default("undefined") ]
[#assign routeNum = timesTable.getRouteID()?default("undefined")?left_pad(3, "0") ]
[#assign dirID    = timesTable.getDir().value()?default("0") ]
[#assign keyID    = timesTable.getKey().value()?default("W") ]
[#assign baseUrl  = "t1" + routeNum + "_" + dirID ]
[#assign htmUrl   = baseUrl + ".htm"]
[#assign pdfUrl   = baseUrl + ".pdf"]
[#assign horizUrl = baseUrl + ".html"]
[#assign mapUrl   = baseUrl + "map.htm"]
[#assign allUrl   = baseUrl + "all.htm"]
[#if   timesTable.getRouteURL()?has_content]
  [#assign routeUrl = timesTable.getRouteURL()]
[#else]
  [#assign routeUrl = "../r" + routeNum + ".htm"]
[/#if]

[#assign alerts   = "<a href=\"${prodPath?default('')}/alerts/#" + routeNum + "\">"]
[#assign alertsLink = alerts + "</a>"]
[#assign alertsUrl  = alerts + "trimet.org/alerts</a>"]

[#assign columns = timesTable.getTimePoints()]
[#assign rows    = timesTable.getTimeTable()]
[#assign name    = timesTable.getRouteName()?default("")]
[#assign dest    = timesTable.getDestination()?default("")]
[#assign key     = timesTable.getKeyName()?default("")]
[#assign now     = Parameters.NOW?string("yyyy")]
[#assign nowDate = Parameters.NOW?string("MM-dd-yyyy")]

[#assign date    = timesTable.getDate()?default(nowDate)]
[#assign prettyDate  = timesTable.getEffectiveDate()?string("MMMM d, yyyy")]
[#assign showStopIDs = timesTable.showStopIDs()]
